'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {createSupabaseBrowserClient} from '@/lib/supabase/browser'
export default function SecurityPage(){
 const [factor,setFactor]=useState<any>(null),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[center,setCenter]=useState<any>(null),[error,setError]=useState(''),[name,setName]=useState(''),[consent,setConsent]=useState({analytics:false,functional:false,marketing:false}),[report,setReport]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const s=createSupabaseBrowserClient();const {data}=await s.auth.mfa.listFactors();setFactor((data?.all??[]).find((x:any)=>x.status==='verified')??null);const r=await fetch('/api/security/center',{cache:'no-store'});if(r.ok){const x=await r.json();setCenter(x);setName(x.profile?.display_name??'');if(x.consent)setConsent({analytics:!!x.consent.analytics,functional:!!x.consent.functional,marketing:!!x.consent.marketing})}}
 useEffect(()=>{load()},[])
 async function post(body:any){const r=await fetch('/api/security/center',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.error||'Falha');return x}
 async function enroll(){setBusy(true);const s=createSupabaseBrowserClient();const {data,error}=await s.auth.mfa.enroll({factorType:'totp',friendlyName:'Open Claude Authenticator'});if(error)setError(error.message);else{setFactor({id:data.id,status:'unverified'});setQr(data.totp.qr_code);setSecret(data.totp.secret)}setBusy(false)}
 async function verify(){setBusy(true);const s=createSupabaseBrowserClient();const c=await s.auth.mfa.challenge({factorId:factor.id});if(c.error){setError(c.error.message);setBusy(false);return}const v=await s.auth.mfa.verify({factorId:factor.id,challengeId:c.data.id,code});if(v.error)setError(v.error.message);else{setQr('');setSecret('');setCode('');await load()}setBusy(false)}
 async function remove(){if(!factor)return;setBusy(true);const r=await createSupabaseBrowserClient().auth.mfa.unenroll({factorId:factor.id});if(r.error)setError(r.error.message);else setFactor(null);setBusy(false)}
 async function action(body:any){try{await post(body);await load()}catch(e){setError(e instanceof Error?e.message:'Falha')}}
 return <main className="shell"><nav className="nav"><Link className="brand" href="/chat">OPEN CLAUDE</Link><Link className="muted" href="/account">Privacidade</Link></nav><section className="chat">
 <div className="card"><h1>Segurança da conta</h1>{factor?.status==='verified'?<><p>✅ MFA/TOTP ativo.</p><button className="button secondary" onClick={remove}>Remover autenticador</button></>:!qr?<button className="button" onClick={enroll} disabled={busy}>Ativar MFA / 2FA</button>:<><img alt="QR Code" src={'data:image/svg+xml;utf8,'+encodeURIComponent(qr)} style={{maxWidth:260}}/><p className="muted">Chave manual: {secret}</p><input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button className="button" onClick={verify} disabled={busy||code.length!==6}>Confirmar MFA</button></>}{error&&<p role="alert">{error}</p>}</div>
 <div className="card" style={{marginTop:16}}><h2>Sessões</h2><p className="muted">Sessão atual: {center?.currentSession?'ativa':'não detectada'}.</p><div className="actions"><button className="button secondary" onClick={()=>action({action:'signoutOthers'})}>Revogar outras sessões</button><button className="button secondary" onClick={async()=>{await action({action:'signoutAll'});location.href='/'}}>Revogar todas</button></div></div>
 <div className="card" style={{marginTop:16}}><h2>Dados pessoais</h2><label>Nome de exibição<input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><button className="button" onClick={()=>action({action:'correction',displayName:name})}>Corrigir dados</button><div className="actions" style={{marginTop:10}}><Link className="button secondary" href="/account">Exportar / excluir</Link></div></div>
 <div className="card" style={{marginTop:16}}><h2>Consentimento e políticas</h2><p className="muted">Versão atual: {center?.policyVersion??'2026-10-07'}</p>{['analytics','functional','marketing'].map(k=><label key={k}><input type="checkbox" checked={(consent as any)[k]} onChange={e=>setConsent({...consent,[k]:e.target.checked})}/> {k}</label>)}<button className="button" onClick={()=>action({action:'consent',...consent})}>Salvar consentimento</button><p className="muted">Histórico de versões aceitas: {(center?.acceptances??[]).length}</p></div>
 <div className="card" style={{marginTop:16}}><h2>Cookies</h2>{(center?.cookies??[]).map((c:any)=><p className="muted" key={c.name}>• {c.name} · {c.category} · {c.duration}</p>)}</div>
 <div className="card" style={{marginTop:16}}><h2>Alertas / denúncia</h2>{(center?.alerts??[]).length?center.alerts.map((a:any)=><div key={a.id}><strong>{a.title}</strong><p className="muted">{a.message}</p><button className="button secondary" onClick={()=>action({action:'acknowledge',id:a.id})}>Marcar lido</button></div>):<p className="muted">Nenhum alerta pendente.</p>}<textarea rows={4} value={report} onChange={e=>setReport(e.target.value)} placeholder="Descreva um incidente, abuso ou solicitação de revisão…"/><button className="button secondary" onClick={async()=>{await action({action:'report',category:'security',description:report});setReport('')}}>Registrar denúncia</button></div>
 </section></main>
