import type { AIModel, AIProviderConfig, AIRequest, AIResponse, AIStreamEvent, AIUsage } from '@/types/ai'
import { calculateCost } from './cost'
import { AIError, errorFromStatus, normalizeAIError } from './errors'
interface Input{provider:AIProviderConfig;model:AIModel;request:AIRequest;apiKey?:string}
function endpoint(p:AIProviderConfig){const b=p.baseUrl.replace(/\/$/,'');return b.endsWith('/v1')?`${b}/messages`:`${b}/v1/messages`}
function timeout(signal:AbortSignal|undefined,ms:number){const c=new AbortController();const t=setTimeout(()=>c.abort('timeout'),ms);const f=()=>c.abort(signal?.reason??'cancelled');if(signal)signal.addEventListener('abort',f,{once:true});return{signal:c.signal,cleanup:()=>{clearTimeout(t);signal?.removeEventListener('abort',f)}}}
function usage(v:any):AIUsage|undefined{if(!v)return;const i=v.input_tokens,o=v.output_tokens;if(i==null&&o==null)return;return{inputTokens:i,outputTokens:o,totalTokens:(i??0)+(o??0)}}
function body(request:AIRequest,model:string,stream:boolean){const system=request.messages.filter(m=>m.role==='system').map(m=>m.content).join('\n\n');const messages=request.messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='tool'?'user':m.role,content:m.content}));return{model,max_tokens:request.maxTokens??4096,messages,...(system?{system}:{}),...(request.temperature!=null?{temperature:request.temperature}:{}),stream}}
export async function completeAnthropic({provider,model,request,apiKey}:Input):Promise<AIResponse>{const started=Date.now();const t=timeout(request.signal,request.timeoutMs??provider.timeoutMs??120000);try{const r=await fetch(endpoint(provider),{method:'POST',signal:t.signal,headers:{'content-type':'application/json','x-api-key':apiKey??'','anthropic-version':'2023-06-01'},body:JSON.stringify(body(request,model.id,false))});if(!r.ok){let d=`HTTP ${r.status}`;try{const x=await r.json() as any;d=x?.error?.message??x?.message??d}catch{}throw errorFromStatus(r.status,d,{provider:provider.id,model:model.id})}const x=await r.json() as any;const content=Array.isArray(x.content)?x.content.filter((b:any)=>b.type==='text').map((b:any)=>b.text).join(''):'';if(!content)throw new AIError({code:'EMPTY_RESPONSE',message:'AI provider returned no text content.',provider:provider.id,model:model.id,retryable:true});const u=usage(x.usage);return{id:x.id??crypto.randomUUID(),model:model.id,provider:provider.id,content,usage:u,cost:calculateCost(u,model),finishReason:x.stop_reason,latencyMs:Date.now()-started}}catch(e){if(request.signal?.aborted)throw new AIError({code:'CANCELLED',message:'AI request cancelled by caller.',provider:provider.id,model:model.id,retryable:false,cause:e});if(t.signal.aborted)throw new AIError({code:'TIMEOUT',message:'AI provider timed out.',provider:provider.id,model:model.id,retryable:true,cause:e});throw normalizeAIError(e,{provider:provider.id,model:model.id})}finally{t.cleanup()}}
export async function* streamAnthropic({provider,model,request,apiKey}:Input):AsyncGenerator<AIStreamEvent>{const t=timeout(request.signal,request.timeoutMs??provider.timeoutMs??120000);try{const r=await fetch(endpoint(provider),{method:'POST',signal:t.signal,headers:{'content-type':'application/json','accept':'text/event-stream','x-api-key':apiKey??'','anthropic-version':'2023-06-01'},body:JSON.stringify(body(request,model.id,true))});if(!r.ok){let d=`HTTP ${r.status}`;try{const x=await r.json() as any;d=x?.error?.message??x?.message??d}catch{}throw errorFromStatus(r.status,d,{provider:provider.id,model:model.id})}if(!r.body)throw new AIError({code:'EMPTY_RESPONSE',message:'AI provider returned no stream body.',provider:provider.id,model:model.id,retryable:true});yield{type:'start',id:crypto.randomUUID(),provider:provider.id,model:model.id};const reader=r.body.getReader();const decoder=new TextDecoder();let buf='';let u:AIUsage|undefined;let finishReason:string|undefined;for(;;){const{done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true}).replace(/\r\n/g,'\n');const frames=buf.split('\n\n');buf=frames.pop()??'';for(const frame of frames){const event=frame.split('\n').find(x=>x.startsWith('event:'))?.slice(6).trim();const line=frame.split('\n').find(x=>x.startsWith('data:'))?.slice(5).trim();if(!line)continue;try{const x=JSON.parse(line) as any;if(event==='content_block_delta'&&x.delta?.text)yield{type:'delta',delta:x.delta.text,provider:provider.id,model:model.id};if(event==='message_delta'){finishReason=x.delta?.stop_reason??finishReason;const nu=usage(x.usage);if(nu){u=nu;yield{type:'usage',usage:nu,provider:provider.id,model:model.id}}}if(event==='message_stop')yield{type:'done',finishReason,provider:provider.id,model:model.id}}catch{}}}const cost=calculateCost(u,model);if(u)yield{type:'usage',usage:u,cost,provider:provider.id,model:model.id};yield{type:'done',finishReason,cost,usage:u,provider:provider.id,model:model.id}}catch(e){const n=request.signal?.aborted?new AIError({code:'CANCELLED',message:'AI stream cancelled by caller.',provider:provider.id,model:model.id,retryable:false,cause:e}):t.signal.aborted?new AIError({code:'TIMEOUT',message:'AI provider timed out.',provider:provider.id,model:model.id,retryable:true,cause:e}):normalizeAIError(e,{provider:provider.id,model:model.id});yield{type:'error',error:n.toJSON(),provider:provider.id,model:model.id};throw n}finally{t.cleanup()}}
