create index if not exists projects_owner_idx on public.projects(owner_id);
create index if not exists project_members_user_idx on public.project_members(user_id);
create index if not exists chats_project_idx on public.chats(project_id);
create index if not exists messages_chat_created_idx on public.messages(chat_id,created_at);
create index if not exists files_project_idx on public.files(project_id);
create index if not exists file_chunks_file_idx on public.file_chunks(file_id);
create index if not exists memories_user_project_idx on public.memories(user_id,project_id);
create index if not exists mcp_connections_user_idx on public.mcp_connections(user_id);
create index if not exists github_connections_user_idx on public.github_connections(user_id);
create index if not exists cowork_sessions_owner_idx on public.cowork_sessions(owner_id);
create index if not exists audit_logs_user_created_idx on public.audit_logs(user_id,created_at desc);
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.files enable row level security;
alter table public.file_chunks enable row level security;
alter table public.memories enable row level security;
alter table public.memory_embeddings enable row level security;
alter table public.mcp_connections enable row level security;
alter table public.tools enable row level security;
alter table public.tool_permissions enable row level security;
alter table public.github_connections enable row level security;
alter table public.cowork_sessions enable row level security;
alter table public.cowork_members enable row level security;
alter table public.permission_grants enable row level security;
alter table public.audit_logs enable row level security;
create policy profiles_self on public.profiles for all to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy projects_select on public.projects for select to authenticated using(owner_id=(select auth.uid()) or exists(select 1 from public.project_members pm where pm.project_id=id and pm.user_id=(select auth.uid())));
create policy projects_insert on public.projects for insert to authenticated with check(owner_id=(select auth.uid()));
create policy projects_update on public.projects for update to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy projects_delete on public.projects for delete to authenticated using(owner_id=(select auth.uid()));
create policy project_members_select on public.project_members for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.projects p where p.id=project_id and p.owner_id=(select auth.uid())));
create policy project_members_write on public.project_members for all to authenticated using(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=(select auth.uid()))) with check(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=(select auth.uid())));
create policy chats_access on public.chats for all to authenticated using(owner_id=(select auth.uid()) or exists(select 1 from public.project_members pm where pm.project_id=project_id and pm.user_id=(select auth.uid()))) with check(owner_id=(select auth.uid()));
create policy messages_access on public.messages for all to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.chats c where c.id=chat_id and(c.user_id=(select auth.uid()) or exists(select 1 from public.project_members pm where pm.project_id=c.project_id and pm.user_id=(select auth.uid()))))) with check(user_id=(select auth.uid()));
create policy files_access on public.files for all to authenticated using(owner_id=(select auth.uid()) or exists(select 1 from public.project_members pm where pm.project_id=project_id and pm.user_id=(select auth.uid()))) with check(owner_id=(select auth.uid()));
create policy file_chunks_access on public.file_chunks for all to authenticated using(exists(select 1 from public.files f where f.id=file_id and(f.owner_id=(select auth.uid()) or exists(select 1 from public.project_members pm where pm.project_id=f.project_id and pm.user_id=(select auth.uid()))))) with check(exists(select 1 from public.files f where f.id=file_id and f.owner_id=(select auth.uid())));
create policy memories_access on public.memories for all to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.project_members pm where pm.project_id=project_id and pm.user_id=(select auth.uid()))) with check(user_id=(select auth.uid()));
create policy memory_embeddings_access on public.memory_embeddings for all to authenticated using(exists(select 1 from public.memories m where m.id=memory_id and m.user_id=(select auth.uid()))) with check(exists(select 1 from public.memories m where m.id=memory_id and m.user_id=(select auth.uid())));
create policy mcp_connections_access on public.mcp_connections for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy tools_access on public.tools for all to authenticated using(owner_id=(select auth.uid()) or owner_id is null) with check(owner_id=(select auth.uid()) or owner_id is null);
create policy tool_permissions_access on public.tool_permissions for all to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.tools t where t.id=tool_id and t.owner_id=(select auth.uid()))) with check(user_id=(select auth.uid()) or exists(select 1 from public.tools t where t.id=tool_id and t.owner_id=(select auth.uid())));
create policy github_connections_access on public.github_connections for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy cowork_sessions_access on public.cowork_sessions for all to authenticated using(owner_id=(select auth.uid()) or exists(select 1 from public.cowork_members cm where cm.session_id=id and cm.user_id=(select auth.uid()))) with check(owner_id=(select auth.uid()));
create policy cowork_members_access on public.cowork_members for all to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.cowork_sessions cs where cs.id=session_id and cs.owner_id=(select auth.uid()))) with check(user_id=(select auth.uid()) or exists(select 1 from public.cowork_sessions cs where cs.id=session_id and cs.owner_id=(select auth.uid())));
create policy permission_grants_access on public.permission_grants for all to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.projects p where p.id=project_id and p.owner_id=(select auth.uid()))) with check(user_id=(select auth.uid()) or exists(select 1 from public.projects p where p.id=project_id and p.owner_id=(select auth.uid())));
create policy audit_logs_select on public.audit_logs for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.projects p where p.id=project_id and p.owner_id=(select auth.uid())));
grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;